
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

image: docker:24-dind

builder:
  stage: build
  script:
    - docker build -t test_project_build:latest
  except:
    - main

deployer:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/fedor/netology/python-api:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/fedor/netology/python-api:latest
  only:
    - main
