
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

variables:
  DOCKER_TLS_CERTDIR: "/certs"

deployer:
  stage: deploy
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind 
  script:
    # - docker build -t $CI_REGISTRY/fedor/netology/python-api:latest .
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker push $CI_REGISTRY/fedor/netology/python-api:latest

    # - docker build -t u91y-gitlab.gitlab.yandexcloud.net:5050/fedor/test-project .
    # - docker login u91y-gitlab.gitlab.yandexcloud.net:5050
    # - docker push u91y-gitlab.gitlab.yandexcloud.net:5050/fedor/test-project

    - docker build -t u91y-gitlab.gitlab.yandexcloud.net:5050/fedor/test-project/hello:gitlab-$CI_COMMIT_SHORT_SHA .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD u91y-gitlab.gitlab.yandexcloud.net:5050
    - docker push u91y-gitlab.gitlab.yandexcloud.net:5050/fedor/test-project/hello:gitlab-$CI_COMMIT_SHORT_SHA
